version: '3'

services:
  keycloak:
    container_name: keycloak
    hostname: keycloak
    image: quay.io/keycloak/keycloak:25.0
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      # KEYCLOAK_EXTRA_ARGS: "-Dkeycloak.import=/opt/keycloak/data/import/"
      # JAVA_OPTS: -Dkeycloak.profile.feature.upload_scripts=enabled
      # KEYCLOAK_IMPORT: /opt/jboss/keycloak/imports/kc.json
    ports:
      - 9909:8080
    networks:
      - edufynet
    volumes:
      - ./:/opt/keycloak/data/import
    command: start-dev --import-realm


networks:
  edufynet:
    name: edufy-network
    external: true